// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAvatar: typeof import('@arco-design/web-vue')['Avatar']
    ABreadcrumb: typeof import("@arco-design/web-vue")["Breadcrumb"]
    ABreadcrumbItem: typeof import("@arco-design/web-vue")["BreadcrumbItem"]
    AButton: typeof import('@arco-design/web-vue')['Button']
    ACheckbox: typeof import("@arco-design/web-vue")["Checkbox"]
    ACol: typeof import('@arco-design/web-vue')['Col']
    AConfigProvider: typeof import("@arco-design/web-vue")["ConfigProvider"]
    ADivider: typeof import('@arco-design/web-vue')['Divider']
    ADoption: typeof import('@arco-design/web-vue')['Doption']
    ADropdown: typeof import('@arco-design/web-vue')['Dropdown']
    AForm: typeof import('@arco-design/web-vue')['Form']
    AFormItem: typeof import('@arco-design/web-vue')['FormItem']
    AInput: typeof import('@arco-design/web-vue')['Input']
    ALayout: typeof import('@arco-design/web-vue')['Layout']
    ALayoutContent: typeof import('@arco-design/web-vue')['LayoutContent']
    ALayoutFooter: typeof import("@arco-design/web-vue")["LayoutFooter"]
    ALayoutHeader: typeof import('@arco-design/web-vue')['LayoutHeader']
    ALayoutSider: typeof import('@arco-design/web-vue')['LayoutSider']
    AMenu: typeof import('@arco-design/web-vue')['Menu']
    AMenuItem: typeof import('@arco-design/web-vue')['MenuItem']
    ARow: typeof import('@arco-design/web-vue')['Row']
    AScrollbar: typeof import("@arco-design/web-vue")["Scrollbar"]
    ASpace: typeof import('@arco-design/web-vue')['Space']
    ASpin: typeof import('@arco-design/web-vue')['Spin']
    ASubMenu: typeof import('@arco-design/web-vue')['SubMenu']
    ATabPane: typeof import("@arco-design/web-vue")["TabPane"]
    ATabs: typeof import("@arco-design/web-vue")["Tabs"]
    ATag: typeof import('@arco-design/web-vue')['Tag']
    ATypographyTitle: typeof import("@arco-design/web-vue")["TypographyTitle"]
    CustomVIew: typeof import('./src/components/CustomVIew/index.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NotFound: typeof import('./src/components/NotFound.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
